alphahorizonio/consumat.io-backend

Procfile
requirements.txt

This enables the public deployment (https://consumat-io-backend.herokuapp.com/). See https://github.com/alphahorizonio/consumat.io/issues/10

Configure Heroku

---

Procfile
README.md
consumatio/external/api.py
requirements.txt

Closes https://github.com/alphahorizonio/consumat.io/issues/14

feat: Change uvicorn to flask

---

consumatio/external/db.py
consumatio/external/tmdb.py

Closes https://github.com/alphahorizonio/consumat.io/issues/13

Backend: Create a caching mechanism to cache API requests

---

README.md
consumatio/external/api.py
consumatio/external/tmdb.py

Closes https://github.com/alphahorizonio/consumat.io/issues/11

feat: Get TMDB API key from environment variable

---

consumatio/external/api.py
consumatio/gateways/movie_credits_to_dict.py
consumatio/gateways/movie_details_to_dict.py
consumatio/gateways/movie_providers_to_dict.py
consumatio/gateways/tv_credits_to_dict.py
consumatio/gateways/tv_details_to_dict.py
consumatio/gateways/tv_providers_to_dict.py
consumatio/usecases/tv_details.py

Closes https://github.com/alphahorizonio/consumat.io/issues/37

Backend: Return "objects" instead of lists

---

consumatio/gateways/movie_providers_to_dict.py

Closes https://github.com/alphahorizonio/consumat.io/issues/22

Backend: Some countries do not have any "flatrate" data when fetching the providers which results in an error

---

consumatio/external/api.schema
consumatio/gateways/movie_gateways/movie_credits_to_dict.py
consumatio/gateways/tv_gateways/tv_credits_to_dict.py
consumatio/gateways/tv_gateways/tv_details_to_dict.py
consumatio/usecases/episode_details.py
consumatio/usecases/movie_details.py
consumatio/usecases/season_details.py
consumatio/usecases/tv_details.py
tests/gateways/tv_gateways/test_tv_details_to_dict.py

Closes https://github.com/alphahorizonio/consumat.io/issues/64

feat: Rename schema properties

---

consumatio/entities/entity.py
consumatio/entities/episode.py
consumatio/entities/movie.py
consumatio/entities/season.py
consumatio/entities/tv.py
consumatio/external/api.py
consumatio/external/db.py
consumatio/external/tmdb.py
consumatio/gateways/episode_gateways/episode_details_to_dict.py
consumatio/gateways/episode_gateways/episode_images_to_dict.py
consumatio/gateways/movie_gateways/movie_credits_to_dict.py
consumatio/gateways/movie_gateways/movie_details_to_dict.py
consumatio/gateways/movie_gateways/movie_images_to_dict.py
consumatio/gateways/movie_gateways/movie_providers_to_dict.py
consumatio/gateways/search_gateways/search_result_to_dict.py
consumatio/gateways/season_gateways/season_details_to_dict.py
consumatio/gateways/season_gateways/season_images_to_dict.py
consumatio/gateways/tv_gateways/tv_credits_to_dict.py
consumatio/gateways/tv_gateways/tv_details_to_dict.py
consumatio/gateways/tv_gateways/tv_images_to_dict.py
consumatio/gateways/tv_gateways/tv_providers_to_dict.py
consumatio/usecases/episode_details.py
consumatio/usecases/movie_details.py
consumatio/usecases/search_details.py
consumatio/usecases/season_details.py
consumatio/usecases/tv_details.py

Closes https://github.com/alphahorizonio/consumat.io/issues/58
This is the first attempt to improve documentation of the project. With this PR I hope to inspire all contributors to add type annotations and docstrings to all future functions and improve said docstrings and annotations on the already documented functions if necessary.

feat: Add type annotations and docstrings to whole project

---

consumatio/external/api.py
consumatio/external/api.schema
consumatio/external/tmdb.py
consumatio/gateways/search_gateways/search_result_to_dict.py
consumatio/usecases/search_details.py

Closes https://github.com/alphahorizonio/consumat.io/issues/55

fix: Remove duplicates in search_result

---

README.md
consumatio/entities/episode.py
consumatio/entities/movie.py
consumatio/entities/season.py
consumatio/entities/tv.py
consumatio/external/api.py
consumatio/external/api.schema
consumatio/external/exceptions.py
consumatio/gateways/movie_gateways/movie_credits_to_dict.py
consumatio/gateways/tv_gateways/tv_credits_to_dict.py
consumatio/usecases/episode_details.py
consumatio/usecases/movie_details.py
consumatio/usecases/search_details.py
consumatio/usecases/season_details.py
consumatio/usecases/tv_details.py

Closes https://github.com/alphahorizonio/consumat.io/issues/69

feat: Use entities in usecases

---

README.md
consumatio/external/api.py
consumatio/external/api.schema
consumatio/external/exceptions.py
consumatio/gateways/movie_gateways/movie_credits_to_dict.py
consumatio/gateways/tv_gateways/tv_credits_to_dict.py
consumatio/usecases/episode_details.py
consumatio/usecases/movie_details.py
consumatio/usecases/search_details.py
consumatio/usecases/season_details.py
consumatio/usecases/tv_details.py

Closes https://github.com/alphahorizonio/consumat.io/issues/76
Closes https://github.com/alphahorizonio/consumat.io/issues/77

feat: Create aliases to translate intern variables to extern ones, remove unused search type from schema

---

consumatio/external/api.py
consumatio/external/api.schema
consumatio/gateways/popular_gateways/popular_movies_to_dict.py
consumatio/gateways/popular_gateways/popular_tv_to_dict.py
consumatio/gateways/search_gateways/search_result_to_dict.py
consumatio/usecases/popular_details.py
consumatio/usecases/search_details.py
tests/gateways/search_gateways/test_search_result_to_dict.py

Closes https://github.com/alphahorizonio/consumat.io/issues/82

feat: Use UnionType for search and popular

---

consumatio/external/api.py
consumatio/external/db.py
consumatio/external/logger.py
consumatio/external/tmdb.py

Closes https://github.com/alphahorizonio/consumat.io/issues/57

feat: Add logging to the externals

---

Procfile
requirements.txt

See https://github.com/alphahorizonio/consumat.io/issues/101

Use gunicorn in production

---

consumatio/usecases/list.py

Closes https://github.com/alphahorizonio/consumat.io/issues/108

fix: Lists return empty lists

---

consumatio/external/api.graphql
consumatio/external/db.py

Closes https://github.com/alphahorizonio/consumat.io/issues/109

fix: Add "None" to watchStatus

---

consumatio/external/api.graphql
consumatio/external/api.py
consumatio/external/tmdb.py
consumatio/gateways/popular_gateways/popular_movies_to_dict.py
consumatio/gateways/popular_gateways/popular_tv_to_dict.py
consumatio/gateways/search_gateways/search_result_to_dict.py
consumatio/gateways/total_pages_gatways/total_pages_to_dict.py
consumatio/usecases/popular_details.py
consumatio/usecases/search_details.py

Closes https://github.com/alphahorizonio/consumat.io/issues/120

fix: Correct representaition of pagination

---

consumatio/external/tmdb.py
consumatio/gateways/popular_gateways/popular_movies_to_dict.py
consumatio/gateways/popular_gateways/popular_tv_to_dict.py
consumatio/gateways/search_gateways/search_result_to_dict.py
consumatio/gateways/total_pages_gatways/total_pages_to_dict.py
consumatio/usecases/popular_details.py
consumatio/usecases/search_details.py

Belongs to https://github.com/alphahorizonio/consumat.io/issues/114

refactor: Remove unnecessary gateway and tmdb requests

---

.github/workflows/docker.yaml
README.md

Closes https://github.com/alphahorizonio/consumat.io/issues/136

Fix CI/CD on PRs

---

consumatio/external/routes.py

Yet another hotfix, this time for the logger API.

Use new logger API

---

Makefile
consumatio/usecases/get_search.py

Closes https://github.com/alphahorizonio/consumat.io/issues/144

fix: Search only returning movies

---

consumatio/usecases/get_by_rating.py

Closes alphahorizonio/consumat.io#147

hotfix: get by rating results missing typename

---

consumatio/external/api/api.graphql
consumatio/external/api/api.py
consumatio/external/db/db.py
consumatio/external/tmdb/tmdb.py
consumatio/usecases/get_by_rating.py
consumatio/usecases/get_episode.py
consumatio/usecases/get_movie.py
consumatio/usecases/get_popular.py
consumatio/usecases/get_search.py
consumatio/usecases/get_season.py
consumatio/usecases/get_season_episodes.py
consumatio/usecases/get_tv.py
consumatio/usecases/get_tv_seasons.py
consumatio/usecases/get_user_i18n.py
consumatio/usecases/get_watch_count.py
consumatio/usecases/get_watch_time.py
consumatio/usecases/set_country.py
consumatio/usecases/set_favorite.py
consumatio/usecases/set_language.py
consumatio/usecases/set_number_of_watched_episodes.py
tests/tmdb/tmdb_mock.py
tests/usecases/test_get_by_rating.py
tests/usecases/test_get_movie.py
tests/usecases/test_get_popular.py
tests/usecases/test_get_tv.py

Closes https://github.com/alphahorizonio/consumat.io/issues/156

feat: i18n for API requests handled by DB

---

consumatio/external/db/db.py
consumatio/usecases/get_by_rating.py
consumatio/usecases/get_episode.py
consumatio/usecases/get_movie.py
consumatio/usecases/get_popular.py
consumatio/usecases/get_search.py
consumatio/usecases/get_season.py
consumatio/usecases/get_tv.py
consumatio/usecases/set_favorite.py
consumatio/usecases/set_number_of_watched_episodes.py
consumatio/usecases/set_rating.py
consumatio/usecases/set_watch_status.py

Closes https://github.com/alphahorizonio/consumat.io/issues/154

refactor: Change defaults in usecases

---

consumatio/external/api/api.graphql
consumatio/external/api/api.py
consumatio/external/tmdb/tmdb.py
consumatio/gateways/popular_gateways/popular_movies_to_dict.py
consumatio/gateways/popular_gateways/popular_tv_to_dict.py
consumatio/usecases/get_discover.py
consumatio/usecases/get_list.py

Closes https://github.com/alphahorizonio/consumat.io/issues/88
Closes https://github.com/alphahorizonio/consumat.io/issues/87

feat: discover endpoint

---

consumatio/external/db/db.py
consumatio/usecases/get_user_i18n.py

Closes https://github.com/alphahorizonio/consumat.io/issues/166
Currently new users don't have a language/country set which causes most TMDB API requests to fail.

fix: create user when i18n queried 
